### PR TITLE
Adding support for tail arguments to GolangRunMojo.

### PR DESCRIPTION
**Pull request by GuillaumeC91**
Adding support for tail arguments to GolangRunMojo. This allows the invocation of GO mains that require CLI arguments i.e. `go run main.go arg1`. Adding new test case for the run mojo, and including new mojoRun.xml test profile.

### CODE REVIEW

**Comment by raydac** [comment]
to add "args" list in run mojo of course a good idea (potentially it duplicates functionality of packages attribute but may be it would be good from point of view user), but what for did you change version? snapshot - means development version and there is not any need to change development version per commit

**Comment by GuillaumeC91** [comment]
@raydac You're right, I just noticed that 2.1.7 has not been released yet. Want me to back the version bump out and add changelog to 2.1.7?

Also, thanks for the awesome plugin!

**Comment by raydac** [comment]
please remove commits related to the version change

**Comment by GuillaumeC91** [comment]
@raydac Reverted version bump commit and updated changelog. If accepted,  [Wiki page](https://github.com/raydac/mvn-golang/wiki/PluginConfigParameters) will also require an update.

**Pull request merged**
